### ISSUE TITLE
Странный баг

### ISSUE THREAD

**Issue by anorudes** [uploadcare/uploadcare-bower#6]
Привет, ребята. Обнаружил странный баг с использованием javascript библиотеки uploadcare в приложение на реакте.
Даже не знаю как правильно его описать. Наиболее заметен он в chrome. 
И так - описываю баг: Как только я подключаю uploadcare.full.js в приложение, то начинается магия)
http://joxi.ru/LmGa100uRL6XGA
html в консоли бесконечно дергается, невозможно поменять стили в консоли. Все начинает тормозить сильно. Сказывается впечатление, что uploadcare бесконечно (с интервалом в пару мс) меняет дом (может запись в аттрибуты какая-то). Долго разбирал весь апп пока не оставил белый экран. Проблема начинается сразу после подключения uploadcare.full.js
Решил тем, что подрубаю его ассинхронно на нужных страницах, но это все равно не выход.

Если включить проффилирование на пустой странице, то выдает следующее:
http://joxi.ru/12MWqNNS4OaPjr
Неважно как долго ждать выполняться будет бесконечно.

Может кто подскажет в какую сторону смотреть )

**Comment by homm** [comment]
Hi there!

This is a known "issue".

The HTML tag is blinking because it is updated when we watch for new widgets on the page. These updates come from jQuery selector's engine, Sizzle. It constantly adds and removes id attribute for the HTML tag.

You have two options how to avoid this:
- disable live initialization 
- manually add any id attribute to your HTML tag.

You can read more about this problem there: http://stackoverflow.com/a/32926475/253146
